name: '${name}'
version: '${version}'
main: '${main}'
depend:
  - PlaceholderAPI
folia-supported: true
api-version: 1.13

commands:
  justtags:
    description: Main command for JustTags
    permission: justtags.command.justtags
    aliases: [jtags, tag, tags]